#!/bin/bash

##### SET VARIABLES #####
### The user must exist on the target host and must have the specified password
creds=~/.dashdb.json
if [ -e $creds ]; then
  host=$(jq -r '.host' $creds)
  user=$(jq -r '.username' $creds)
  password=$(jq -r '.password' $creds)
else
  echo "No credentials: $creds"
  exit
fi

### Identify an administrative user on the system. If $user is an admin this field should be set to the same value.
#useradm=blutestadmin

userUppercase=$(echo "$user" | tr '[:lower:]' '[:upper:]')

echo
echo "Running on host $host as user $user"
echo

##### GET AUTHENTICATION TOKENS #####
# Authorize the current user
authResponse=$(curl -k -X POST "https://$host/dashdb-api/v2/auth" -d '{"userid":"'$user'", "password":"'$password'"}')
authToken=$(echo $authResponse | sed -e 's/{ "userid": "[a-zA-Z0-9]*", "token": "/''/g' | sed -e 's/" }/''/g')

echo
echo "Using access token: $authToken"
echo

# Grab the authentication tokens for Aspera, S3, and SoftLayer
asperaResponse=$(curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/aspera" -d '{}')
asperaToken=$(echo $asperaResponse | sed -e 's/{ "aspera_token": "/''/g' | sed -e 's/", "userid": "[a-zA-Z0-9]*" }/''/g')

echo
echo "Using aspera token: $asperaToken"
echo

#s3Response=$(curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/s3_storage_explorer" -d '{"endpoint":"s3.amazonaws.com","s3_access_key":"AKIAIYBWTHXXW44MMOJA","s3_secret_access_key":"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"}')
#s3Token=$(echo $s3Response | sed  -e 's/{"token":"/''/g' | sed -e 's/"}/''/g')

#softlayerResponse=$(curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}')
#softlayerToken=$(echo $softlayerResponse | sed  -e 's/{"token":"/''/g' | sed -e 's/"}/''/g')

##### RUN APIs #####

curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users/blutest/achievements"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users/invalidUser/achievements"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users/blutest/achievements/tours?check=intro&console=webui"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/version"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/s3_storage_explorer" -d '{"endpoint":"s3.amazonaws.com","s3_access_key":"AKIAIYBWTHXXW44MMOJA","s3_secret_access_key":"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"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/aspera" -d '{}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786_Invalid","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba_Invalid"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schemas" -d '{"name":"ALBACORE_TEST_SCHEMA_NONADMIN"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/schemas"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/schemas/SAMPLES"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/schemas/$userUppercase/tables/TB_ALL_DATATYPES"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/schemas/SAMPLES/tables"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables" -d '{"name":"TEST_TABLE","schema":"ALBACORE_SCHEMA_FOR_TESTING","columns":[{"name":"COL1","datatype_ddl":"INT","nullable":"no"},{"name":"COL2","datatype_ddl":"VARCHAR(255)","nullable":"yes"},{"name":"COL3","datatype_ddl":"DECIMAL","nullable":"yes"},{"name":"COL4","datatype_ddl":"SMALLINT","nullable":"yes"},{"name":"COL5","datatype_ddl":"BIGINT","nullable":"yes"},{"name":"COL6","datatype_ddl":"DECIMAL(3,2)","nullable":"yes"},{"name":"COL7","datatype_ddl":"DECIMAL(10)","nullable":"yes"},{"name":"COL8","datatype_ddl":"CHAR","nullable":"yes"},{"name":"COL9","datatype_ddl":"CHAR(128)","nullable":"yes"},{"name":"COL10","datatype_ddl":"DATE","nullable":"yes"},{"name":"COL11","datatype_ddl":"TIME","nullable":"yes"},{"name":"COL12","datatype_ddl":"TIMESTAMP","nullable":"yes"}]}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables" -d '{"name":"TEST_TABLE_FAIL","schema":"ALBACORE_SCHEMA_FOR_TESTING","columns":[{"name":"COL1","datatype_ddl":"INT","nullable":"no"},{"name":"COL1","datatype_ddl":"VARCHAR(255)","nullable":"yes"}]}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables" -d '{"name":"TEST_TABLE_FAIL","schema":"ALBACORE_SCHEMA_FOR_TESTING","columns":[{"name":"COL1","datatype_ddl":"DECIMAL(33)","nullable":"no"}]}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables" -d '{"name":"TEST_TABLE_TWO","schema":"ALBACORE_SCHEMA_FOR_TESTING","columns":[{"name":"COL1","datatype_ddl":"INT","nullable":"no"},{"name":"COL2","datatype_ddl":"VARCHAR(255)","nullable":"yes"},{"name":"COL3","datatype_ddl":"DECIMAL","nullable":"yes"},{"name":"COL4","datatype_ddl":"SMALLINT","nullable":"yes"},{"name":"COL5","datatype_ddl":"BIGINT","nullable":"yes"},{"name":"COL6","datatype_ddl":"DECIMAL(3,2)","nullable":"yes"},{"name":"COL7","datatype_ddl":"DECIMAL(10)","nullable":"yes"},{"name":"COL8","datatype_ddl":"CHAR","nullable":"yes"},{"name":"COL9","datatype_ddl":"CHAR(128)","nullable":"yes"},{"name":"COL10","datatype_ddl":"DATE","nullable":"yes"},{"name":"COL11","datatype_ddl":"TIMESTAMP","nullable":"yes"}]}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/connections"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/monitor/connections/12;fda"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/monitor/connections/999999"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schemas" -d '{"name":"ALBACORE_TEST_SCHEMA"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schemas" -d '{"invalid_parameter":"ALBACORE_TEST_SCHEMA"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schemas" -d '{}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/schemas/SAMPLES"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/connections"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/monitor/connections/127658"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage/history"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage/history"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage/by_schema"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage/by_schema/ALBACORE_NONEXISTING"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage/by_schema/GOSALES/by_partition"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage/by_schema/ALBACORE_NONEXISTING"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage/by_schema/GOSALES"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage/by_schema/SAMPLES"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage/by_schema/GOSALES/by_partition"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage/by_schema/SAMPLES/by_partition"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/home"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/home/RSamples"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/home/RSamples/arule_gosales.R"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/home/nonexistingpath/somefile"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/home/RSamples/nonexistingFile.txt"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/home/nonexistingfile123.csv"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"S3","table":"NON_EXISTING_TABLE_SDLKFJLSKDJFOI","load_action":"INSERT","schema":"NON_EXISTING_SCHEMAALSKJFOEINV","cloud_source":{"endpoint":"s3.amazonaws.com","path":"dashdb::sfpd_incident_2013.csv","auth_id":"AKIAIYBWTHXXW44MMOJA","auth_secret":"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"},"max_warning_count":99,"file_options":{"column_delimiter":","}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"S3","load_action":"INSERT","schema":"'$userUppercase'","table":"LOAD_S3_TABLE","cloud_source":{"endpoint":"s3.amazonaws.com","path":"dashdb::sfpd_incident_2013.csv","auth_id":"AKIAIYBWTHXXW44MMOJA","auth_secret":"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"},"max_warning_count":99}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"S3","load_action":"INSERT","schema":"'$userUppercase'","table":"LOAD_S3_TABLE","cloud_source":{"endpoint":"s3.amazonaws.com","path":"dashdb::sfpd_incident_2013.csv","auth_secret":"UXlJRLliPMmjFPqPlGQL4A1aOht8PNeLl58WlIg1"},"max_warning_count":99}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SOFTLAYER","load_action":"INSERT","schema":"'$userUppercase'","table":"LOAD_SOFTLAYER_TABLE","cloud_source":{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","path":"connectordata::customers1.csv","auth_id":"IBMOS283639-3:ibm132786","auth_secret":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"},"max_warning_count":99}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SOFTLAYER","load_action":"INSERT","schema":"'$userUppercase'","table":"LOAD_SOFTLAYER_TABLE","cloud_source":{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","path":"connectordata::customers1.csv","auth_secret":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"},"max_warning_count":99}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"S3","table":"NON_EXISTING_TABLE_SDLKFJLSKDJFOI","load_action":"INSERT","schema":"NON_EXISTING_SCHEMAALSKJFOEINV","cloud_source":{"endpoint":"s3.amazonaws.com","path":"dashdb::sfpd_incident_2013.csv","auth_id":"AKIAIYBWTHXXW44MMOJA","auth_secret":"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"},"max_warning_count":99,"file_options":{"column_delimiter":","}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"S3","load_action":"INSERT","schema":"'$userUppercase'","table":"LOAD_S3_TABLE","cloud_source":{"endpoint":"s3.amazonaws.com","path":"dashdb::sfpd_incident_2013.csv","auth_id":"AKIAIYBWTHXXW44MMOJA","auth_secret":"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"},"max_warning_count":99}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"S3","load_action":"INSERT","schema":"'$userUppercase'","table":"LOAD_S3_TABLE","cloud_source":{"endpoint":"s3.amazonaws.com","path":"dashdb::sfpd_incident_2013.csv","auth_secret":"UXlJRLliPMmjFPqPlGQL4A1aOht8PNeLl58WlIg1"},"max_warning_count":99}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SOFTLAYER","load_action":"INSERT","schema":"'$userUppercase'","table":"LOAD_SOFTLAYER_TABLE","cloud_source":{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","path":"connectordata::customers1.csv","auth_id":"IBMOS283639-3:ibm132786","auth_secret":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"},"max_warning_count":99}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SOFTLAYER","load_action":"INSERT","schema":"'$userUppercase'","table":"LOAD_SOFTLAYER_TABLE","cloud_source":{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","path":"connectordata::customers1.csv","auth_secret":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"},"max_warning_count":99}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/resources"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/resources/dashdb-ssl-certificate"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/resources/non-existing-id"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":",","includes_header":"yes","data":"Title, Year, Producer\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott\n\"The Sequel to \"\"Dances With Wolves.\"\"\",1982, Ridley Scott\nBlades of Glory,2012, Sidney Ahlstrom\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":"0x2C","includes_header":"yes","data":"Title, Year, Producer\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott\n\"The Sequel to \"\"Dances With Wolves.\"\"\",1982, Ridley Scott\nBlades of Glory,2012, Sidney Ahlstrom\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":"0x09","includes_header":"yes","data":"Title\t Year\t Producer\nCity of God\t2002\t Katia Lund\nRain\t1292\t Christine Jeffs\n2001: A Space Odyssey\t1969\t Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\"\t1957\t Sidney Lumet\nAlien\t1979\t Ridley Scott\n\"The Sequel to \"\"Dances With Wolves.\"\"\"\t1982\t Ridley Scott\nBlades of Glory\t2012\t Sidney Ahlstrom\nCity of God\t2002\t Katia Lund\nRain\t1292\t Christine Jeffs\n2001: A Space Odyssey\t1969\t Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\"\t1957\t Sidney Lumet\nAlien\t1979\t Ridley Scott"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":"0xJ1","includes_header":"yes","data":"Title, Year, Producer\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott\n\"The Sequel to \"\"Dances With Wolves.\"\"\",1982, Ridley Scott\nBlades of Glory,2012, Sidney Ahlstrom\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":"0x0D","includes_header":"yes","data":"Title, Year, Producer\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott\n\"The Sequel to \"\"Dances With Wolves.\"\"\",1982, Ridley Scott\nBlades of Glory,2012, Sidney Ahlstrom\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":",","includes_header":"yeasdfs","data":"Title, Year, Producer\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott\n\"The Sequel to \"\"Dances With Wolves.\"\"\",1982, Ridley Scott\nBlades of Glory,2012, Sidney Ahlstrom\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":",asdf","includes_header":"yes","data":"Title, Year, Producer\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott\n\"The Sequel to \"\"Dances With Wolves.\"\"\",1982, Ridley Scott\nBlades of Glory,2012, Sidney Ahlstrom\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":",","includes_header":"yes","dataaaasdf":"Title, Year, Producer\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott\n\"The Sequel to \"\"Dances With Wolves.\"\"\",1982, Ridley Scott\nBlades of Glory,2012, Sidney Ahlstrom\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n\"This is a \"\"fake\"\" movie title\",1957, Sidney Lumet\nAlien,1979, Ridley Scott"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":"|","includes_header":"yes","data":"Title, Year, Producer\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n'"This is a  ' 'fake ' ' movie title "',1957, Sidney Lumet\nAlien,1979, Ridley Scott\n'"The Sequel to  ' 'Dances With Wolves. ' ' "',1982, Ridley Scott\nBlades of Glory,2012, Sidney Ahlstrom\nCity of God,2002, Katia Lund\nRain,1292, Christine Jeffs\n2001: A Space Odyssey,1969, Stanley Kubrick\n'"This is a  ' 'fake ' ' movie title "',1957, Sidney Lumet\nAlien,1979, Ridley Scott"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":",","includes_header":"yes","data":"1,Eldon Base for stackable storage shelf platinum,-213.25,0.8,4300000000,a,2016-12-06,12:00,2016-12-06 13:00\n2,1.7 Cubic Foot Compact Cube Office Refrigerators,457.81,0.58,4304567839,b,2016-12-07,13:00,2016-12-07 13:00\n3,Cardinal Slant-D® Ring Binder Heavy Gauge Vinyl,46.71,0.39,4309135678,c,2016-12-08,14:00,2016-12-08 14:00\n4,R380,1198.97,0.58,4313703517,d,2016-12-09,15:00,2016-12-09 15:00\n5,Holmes HEPA Air Purifier,30.94,0.5,4318271356,e,2016-12-10,16:00,2016-12-10 16:00\n6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,4.43,0.37,4322839195,f,2016-12-11,17:00,2016-12-11 17:00\n7,Angle-D Binders with Locking Rings Label Holders,-54.04,0.38,4327407034,g,2016-12-12,18:00,2016-12-12 18:00\n8,SAFCO Mobile Desk Side File Wire Frame,127.7,0.32,4331974873,h,2016-12-13,19:00,2016-12-13 19:00\n9,SAFCO Commercial Wire Shelving Black,-695.26,0.54,4336542712,i,2016-12-14,20:00,2016-12-14 20:00\n10,Xerox 198,-226.36,0.38,4776847016,j,2016-12-15,21:00,2016-12-15 13:00\n11,Xerox 1980,-166.85,0.4,5217151320,k,2016-12-16,22:00,2016-12-16 13:00\n12,Advantus Map Pennant Flags and Round Head Tacks,-14.33,0.53,5657455624,l,2016-12-17,23:00,2016-12-17 13:00\n13,Holmes HEPA Air Purifier,134.72,0.5,6097759928,m,2016-12-18,12:00,2016-12-18 13:00\n14,DS/HD IBM Formatted Diskettes 200/Pack - Staples,114.46,0.71,6538064232,n,2016-12-19,13:00,2016-12-19 13:00\n15,Wilson Jones 1 Hanging DublLock® Ring Binders,-4.72,0.37,6978368536,o,2016-12-20,14:00,2016-12-20 13:00\n16,Ultra Commercial Grade Dual Valve Door Closer,782.91,0.53,7418672840,p,2016-12-21,15:00,2016-12-21 13:00\n17,#10-4 1/8 x 9 1/2 Premium Diagonal Seam Envelopes,93.8,0.4,7858977144,q,2016-12-22,16:00,2016-12-22 13:00\n18,Hon 4-Shelf Metal Bookcases,440.72,0.6,8299281448,r,2016-12-23,17:00,2016-12-23 13:00\n19,Lesro Sheffield Collection Coffee Table End Table Center Table Corner Table,-481.04,0.68,8739585752,s,2016-12-24,18:00,2016-12-24 13:00\n20,g520,-11.68,0.59,9179890056,t,2016-12-25,19:00,2016-12-25 13:00\n21,LX 788,313.58,0.58,9620194360,u,2016-12-26,20:00,2016-12-26 13:00\n22,Avery 52,26.92,0.38,4300000043,v,2016-12-27,21:00,2016-12-27 13:00\n23,Plymouth Boxed Rubber Bands by Plymouth,-5.77,0.8,4300000086,w,2016-12-28,22:00,2016-12-28 13:00\n24,GBC Pre-Punched Binding Paper Plastic White 8-1/2 x 11,-172.88,0.37,4300000129,x,2016-12-29,23:00,2016-12-29 13:00"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schema_discovery" -d '{"column_separator":",","includes_header":"no","data":"1,Eldon Base for stackable storage shelf platinum,-213.25,0.8,4300000000,a,2016-12-06,12:00,2016-12-06 13:00\n2,1.7 Cubic Foot Compact Cube Office Refrigerators,457.81,0.58,4304567839,b,2016-12-07,13:00,2016-12-07 13:00\n3,Cardinal Slant-D® Ring Binder Heavy Gauge Vinyl,46.71,0.39,4309135678,c,2016-12-08,14:00,2016-12-08 14:00\n4,R380,1198.97,0.58,4313703517,d,2016-12-09,15:00,2016-12-09 15:00\n5,Holmes HEPA Air Purifier,30.94,0.5,4318271356,e,2016-12-10,16:00,2016-12-10 16:00\n6,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,4.43,0.37,4322839195,f,2016-12-11,17:00,2016-12-11 17:00\n7,Angle-D Binders with Locking Rings Label Holders,-54.04,0.38,4327407034,g,2016-12-12,18:00,2016-12-12 18:00\n8,SAFCO Mobile Desk Side File Wire Frame,127.7,0.32,4331974873,h,2016-12-13,19:00,2016-12-13 19:00\n9,SAFCO Commercial Wire Shelving Black,-695.26,0.54,4336542712,i,2016-12-14,20:00,2016-12-14 20:00\n10,Xerox 198,-226.36,0.38,4776847016,j,2016-12-15,21:00,2016-12-15 13:00\n11,Xerox 1980,-166.85,0.4,5217151320,k,2016-12-16,22:00,2016-12-16 13:00\n12,Advantus Map Pennant Flags and Round Head Tacks,-14.33,0.53,5657455624,l,2016-12-17,23:00,2016-12-17 13:00\n13,Holmes HEPA Air Purifier,134.72,0.5,6097759928,m,2016-12-18,12:00,2016-12-18 13:00\n14,DS/HD IBM Formatted Diskettes 200/Pack - Staples,114.46,0.71,6538064232,n,2016-12-19,13:00,2016-12-19 13:00\n15,Wilson Jones 1 Hanging DublLock® Ring Binders,-4.72,0.37,6978368536,o,2016-12-20,14:00,2016-12-20 13:00\n16,Ultra Commercial Grade Dual Valve Door Closer,782.91,0.53,7418672840,p,2016-12-21,15:00,2016-12-21 13:00\n17,#10-4 1/8 x 9 1/2 Premium Diagonal Seam Envelopes,93.8,0.4,7858977144,q,2016-12-22,16:00,2016-12-22 13:00\n18,Hon 4-Shelf Metal Bookcases,440.72,0.6,8299281448,r,2016-12-23,17:00,2016-12-23 13:00\n19,Lesro Sheffield Collection Coffee Table End Table Center Table Corner Table,-481.04,0.68,8739585752,s,2016-12-24,18:00,2016-12-24 13:00\n20,g520,-11.68,0.59,9179890056,t,2016-12-25,19:00,2016-12-25 13:00\n21,LX 788,313.58,0.58,9620194360,u,2016-12-26,20:00,2016-12-26 13:00\n22,Avery 52,26.92,0.38,4300000043,v,2016-12-27,21:00,2016-12-27 13:00\n23,Plymouth Boxed Rubber Bands by Plymouth,-5.77,0.8,4300000086,w,2016-12-28,22:00,2016-12-28 13:00\n24,GBC Pre-Punched Binding Paper Plastic White 8-1/2 x 11,-172.88,0.37,4300000129,x,2016-12-29,23:00,2016-12-29 13:00"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/settings"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/settings"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/settings"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_query_export" -d '{"command":"SELECT 1000, 'ABC"', TIMESTAMP('2001-02-03 04:05:06.00000') FROM SYSCAT.TABLES LIMIT 5"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_query_export" -d '{"command":"SELECT tabschema, tabname FROM syscat.tables WHERE tabname like 'COUNTRY' AND tabschema LIKE 'GOSAL%'"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_query_export" -d '{}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_query_export" -d '{"command":"-- nothing to execute"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_query_export" -d '{"command":"--only one stmt \n insert into gosales.country values ('1"', 2)"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/monitor/storage"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users/blutest/connection_privileges"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutest/connection_privileges" -d '{"userid":"'$user'","restricted":"yes","authorized_hosts":["goog!e.com"]}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutest/connection_privileges" -d '{"userid":"'$user'","restricted":"no","authorized_hosts":["1.1.1.1"]}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutest/connection_privileges" -d '{"userid":"'$user'","restricted":"yes","authorized_hosts":["9.30.167.199","cnn.com"]}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutest/connection_privileges" -d '{"userid":"'$user'","restricted":"yes","authorized_hosts":["1.1.1.1","127.0.0.1","2001:0DB8:0000:0000:0008:0800:200C:417A","localhost"]}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users/blutest/connection_privileges"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutest/connection_privileges" -d '{"userid":"'$user'","restricted":"yes"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutest/connection_privileges" -d '{"userid":"'$user'","restricted":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users/blutest"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users/1qaz2wsx3edc4rfv5gb6yhn7ujm8gsadfsafasaf"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/users" -d '{"id":"blutestadd","name":"John Doe","email":"john.doe@john.com","password":"W0nderland!!","role":"bluusers"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/users" -d '{"id":"'$user'","name":"John Doe","email":"john.doe@john.com","password":"W0nderland!!","role":"bluusers"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/users" -d '{"name":"John Doe","email":"john.doe@john.com","password":"W0nderland!!","role":"bluusers"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/users" -d '{"id":"bluadd2","name":"John Doe","email":"john.doe@john.com","role":"bluusers"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/users" -d '{"id":"bluadd2","password":"Wonderland!!","name":"John Doe","email":"john.doe@john.com","role":"bluusers"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/users" -d '{"id":"bluadd2","password":"w0nderland!!","name":"John Doe","email":"john.doe@john.com","role":"bluusers"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/users" -d '{"id":"bluadd2","password":"W0NDERLAND!!","name":"John Doe","email":"john.doe@john.com","role":"bluusers"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/users" -d '{"id":"bluadd2","password":"W0nderlandii","name":"John Doe","email":"john.doe@john.com","role":"bluusers"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutestadd" -d '{"id":"blutestadd","name":"John Donut"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutest" -d '{"id":"blutestadd2","name":"John Donut"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/1qaz2wsx3edc4rfv5gb6yhn7ujm8gsadfsafasaf" -d '{"id":"1qaz2wsx3edc4rfv5gb6yhn7ujm8gsadfsafasaf","name":"Fail test"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutestadd" -d '{"id":"blutestadd","old_password":"W0nderland!!","new_password":"Wonderland!!"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutestadd" -d '{"id":"blutestadd","old_password":"W0nderland!!","new_password":"w0nderland!!"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutestadd" -d '{"id":"blutestadd","old_password":"W0nderland!!","new_password":"W0NDERLAND!!"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutestadd" -d '{"id":"blutestadd","old_password":"W0nderland!!","new_password":"W0nderlandii"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutestadd" -d '{"id":"blutestadd","old_password":"W0nderland!!","new_password":"Am3ricanG1rl!"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/users/blutestadd"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/users/blutestadmin"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/users/1qaz2wsx3edc4rfv5gb6yhn7ujm8gsadfsafasaf"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users/blutest"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users/bluadmin"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/users" -d '{"id":"blutestadd","name":"John Doe","email":"john.doe@john.com","password":"W0nderland!!","role":"bluusers"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/blutest" -d '{"id":"'$user'","name":"John Donut"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X PUT "https://$host/dashdb-api/v2/users/1qaz2wsx3edc4rfv5gb6yhn7ujm8gsadfsafasaf" -d '{"id":"1qaz2wsx3edc4rfv5gb6yhn7ujm8gsadfsafasaf","name":"Fail test"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/users/blutest"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/users/1qaz2wsx3edc4rfv5gb6yhn7ujm8gsadfsafasaf"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/users"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/home/order_details_header_small.csv"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/home/newDirectory/tiny_table_3col.csv"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/home_content/sample.json"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/home/sample.json"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/home/upload0000"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc?path=nonExistentPathBlahBlahBlah"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc?path=dashdb"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc?path=dashdb"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc?path=dashdb"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc?path=ibm.dashdb.public::convoy-objectstore"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc?path=ibm.dashdb.public::convoy-objectstore"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc?path=ibm.dashdb.public::convoy-objectstore"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/6060c71c-0aa4-4505-b74b-3c77c741c6fc?path=ibm.dashdb.public::convoy-objectstore"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/s3_storage_explorer" -d '{"endpoint":"s3.amazonaws.com","s3_access_key":"AKIAIYBWTHXXW44MMOJAasdfasdfsadf","s3_secret_access_key":"UXlJRLliPMmjFPqPlGQL4A1aOht8PNeLl58WlIg1"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/s3_storage_explorer" -d '{"endpoint":"s3.amazonaws.com","s3_access_key":"AKIAIYBWTHXXW44MMOJA","s3_secret_access_key":"UXlJRLliPMmjFPqPlGQL4A1aOht8PNeLl58WlIg1asdf"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/s3_storage_explorer/invalidToken"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/aspera/$asperaToken"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/aspera/$asperaToken?filename=nonexistingfilename"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/softlayer_storage_explorer/8d37d531-236f-45c5-ae24-6f55340f3dcd"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables/TEST_TABLE"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables/TEST_TABLE/data"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables/TEST_TABLE_TWO/data"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/schemas"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/schemas" -d '{"name":"ALBACORE_TEST_SCHEMA"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/load_jobs/ed244ca8-9b56-4aea-80cb-4943e9cdc2ec"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/load_jobs/a8b5e81f-6ed7-4b4c-a465-f4387bfa4427"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/load_jobs/687f0d11-13c5-4d8c-baca-f18d065c9620"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/load_jobs/c6159999-0953-4242-b069-6f803502b1e9"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/home/order_details_header_small.csv"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables/TEST_TABLE"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables/TEST_TABLE_TWO"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/schemas/ALBACORE_TEST_SCHEMA"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/softlayer_storage_explorer/9b8274be-bf59-4e56-bdaf-e4bb37592525"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables/TEST_TABLE/data"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables/TEST_TABLE"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/schemas/ALBACORE_SCHEMA_FOR_TESTING/tables/TEST_TABLE"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X DELETE "https://$host/dashdb-api/v2/schemas/ALBACORE_TEST_SCHEMA"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/schemas/ALBACORE_TEST_SCHEMA"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/softlayer_storage_explorer/9cfb8ee7-d906-4d63-92c1-9c8279159f56?path=TMP"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/softlayer_storage_explorer/4a9afb1a-a00e-4045-871a-be23b1637360?path=TMP"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/softlayer_storage_explorer/328557de-355f-4950-b8fb-46e2993f6975?path=nonexistentpath"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/softlayer_storage_explorer/c2daa196-f0ef-48cc-8c24-897d1a965709?path=TMP::raguk"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/softlayer_storage_explorer/57bde23e-18d8-4f1a-b354-36ee2f534162?path=TMP::raguk"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/softlayer_storage_explorer/invalidToken"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/softlayer_storage_explorer/f1a1319e-9287-4a62-bc6a-6cde56219542?path=TMP::ckugbndoprn"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/softlayer_storage_explorer" -d '{"endpoint":"https://dal05.objectstorage.softlayer.net/auth/v1.0","username":"IBMOS283639-3:ibm132786","api_key":"91ba722a7263c89ad6a5dedf74fbb6c41b4ffc04e23715a256c2680c9613b1ba"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X GET "https://$host/dashdb-api/v2/softlayer_storage_explorer/b420f2d5-ff2c-4c22-bcaf-c2fdce4fb2d1?path=TMP/raguk"
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SERVER","load_action":"INSERT","schema":"'$userUppercase'","table":"TINY_TABLE_CP1","max_row_count":0,"max_warning_count":1000,"server_source":{"file_path":"tiny_table.csv"},"file_options":{"code_page":"1208","has_header_row":"no","column_delimiter":",","string_delimiter":"\"","date_format":"YYYY-MM-DD","time_format":"HH:MM:SS","timestamp_format":"YYYY-MM-DD HH:MM:SS"}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SERVER","load_action":"INSERT","schema":"'$userUppercase'","table":"TINY_TABLE_CP2","max_row_count":0,"max_warning_count":1000,"server_source":{"file_path":"tiny_table_cp1383.csv"},"file_options":{"code_page":"1383","has_header_row":"no","column_delimiter":",","string_delimiter":"\"","date_format":"YYYY-MM-DD","time_format":"HH:MM:SS","timestamp_format":"YYYY-MM-DD HH:MM:SS"}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SERVER","load_action":"INSERT","schema":"'$userUppercase'","table":"TINY_TABLE_CP3","max_row_count":0,"max_warning_count":1000,"server_source":{"file_path":"tiny_table.csv"},"file_options":{"has_header_row":"no","column_delimiter":",","string_delimiter":"\"","date_format":"YYYY-MM-DD","time_format":"HH:MM:SS","timestamp_format":"YYYY-MM-DD HH:MM:SS"}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SERVER","load_action":"INSERT","schema":"'$userUppercase'","table":"TINY_TABLE_CP4","max_row_count":0,"max_warning_count":1000,"server_source":{"file_path":"tiny_table.csv"},"file_options":{"code_page":"","has_header_row":"no","column_delimiter":",","string_delimiter":"\"","date_format":"YYYY-MM-DD","time_format":"HH:MM:SS","timestamp_format":"YYYY-MM-DD HH:MM:SS"}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SERVER","load_action":"INSERT","schema":"'$userUppercase'","table":"TINY_TABLE","max_row_count":0,"max_warning_count":1000,"server_source":{"file_path":"tiny_table.csv"},"file_options":{"code_page":" ","has_header_row":"no","column_delimiter":",","string_delimiter":"\"","date_format":"YYYY-MM-DD","time_format":"HH:MM:SS","timestamp_format":"YYYY-MM-DD HH:MM:SS"}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SERVER","load_action":"INSERT","schema":"'$userUppercase'","table":"TINY_TABLE","max_row_count":0,"max_warning_count":1000,"server_source":{"file_path":"tiny_table.csv"},"file_options":{"code_page":"dfe","has_header_row":"no","column_delimiter":",","string_delimiter":"\"","date_format":"YYYY-MM-DD","time_format":"HH:MM:SS","timestamp_format":"YYYY-MM-DD HH:MM:SS"}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SERVER","load_action":"INSERT","schema":"'$userUppercase'","table":"TINY_TABLE","max_row_count":0,"max_warning_count":1000,"server_source":{"file_path":"tiny_table.csv"},"file_options":{"code_page":"-2","has_header_row":"no","column_delimiter":",","string_delimiter":"\"","date_format":"YYYY-MM-DD","time_format":"HH:MM:SS","timestamp_format":"YYYY-MM-DD HH:MM:SS"}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SERVER","load_action":"INSERT","schema":"'$userUppercase'","table":"TINY_TABLE","max_row_count":0,"max_warning_count":1000,"server_source":{"file_path":"tiny_table.csv"},"file_options":{"code_page":"12345678","has_header_row":"no","column_delimiter":",","string_delimiter":"\"","date_format":"YYYY-MM-DD","time_format":"HH:MM:SS","timestamp_format":"YYYY-MM-DD HH:MM:SS"}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SERVER","load_action":"INSERT","schema":"'$userUppercase'","table":"TINY_TABLE","max_row_count":0,"max_warning_count":1000,"server_source":{"file_path":"tiny_table.csv"},"file_options":{"code_page":["carrots","rock"],"has_header_row":"no","column_delimiter":",","string_delimiter":"\"","date_format":"YYYY-MM-DD","time_format":"HH:MM:SS"}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/load_jobs" -d '{"load_source":"SERVER","load_action":"INSERT","schema":"'$userUppercase'","table":"TINY_TABLE","max_row_count":0,"max_warning_count":1000,"server_source":{"file_path":"tiny_table.csv"},"file_options":{"code_page":{"carrots":"rock"},"has_header_row":"no","column_delimiter":",","string_delimiter":"\"","date_format":"YYYY-MM-DD","time_format":"HH:MM:SS","timestamp_format":"YYYY-MM-DD HH:MM:SS"}}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"commands":"","limit":1,"stop_on_error":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","limit":1,"stop_on_error":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","commands":"SELECT * FROM SYSCAT.TABLES","stop_on_error":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","commands":"","limit":1}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","commands":"","limit":1,"stop_on_error":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","commands":"create table sqleditor_test (i1 int, c1 varchar(256))","limit":1,"stop_on_error":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","commands":";;;;","limit":1,"stop_on_error":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","commands":"drop table sqleditor_test;","limit":1,"stop_on_error":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","commands":"drop table sqleditor_test2; create table sqleditor_test2 (i1 int, c1 varchar(256));insert into sqleditor_test2 values (0,'A');insert into sqleditor_test2 values (1,'B');insert into sqleditor_test2 values (2,'C');update sqleditor_test2 set i1=1;","limit":1,"stop_on_error":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","commands":"update SQLEDITOR_TEST_TABLE1 set COL1='end';","limit":1,"stop_on_error":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","commands":"select branch_code from gosales.branch where branch_code=6;           ","limit":10,"stop_on_error":"no"}'
curl -k -H "Content-Type: application/json" -H "Authorization: Bearer $authToken" -X POST "https://$host/dashdb-api/v2/sql_jobs" -d '{"separator":";","commands":"select branch_code from gosales.branch order by branch_code desc;","limit":1,"stop_on_error":"no"}'
