- id: auto_light_on_enabled
  alias: auto_light_on_enabled
  trigger:
    platform: state
    entity_id: input_slider.auto_light_minutes, input_slider.auto_light_duration
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - automation.auto_light_on
  - service: homeassistant.turn_on
    data:
      entity_id:
        - automation.auto_light_off

- id: auto_light_on
  alias: auto_light_on
  initial_state: True
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 10
  condition:
    - condition: template
      value_template: '{{ (now().strftime("%s") | int | timestamp_custom("%H:%M")) == states.sensor.auto_light_start.state }}'
  action:
    - service: homeassistant.turn_on
      entity_id: "group.lights"

- id: auto_light_off
  alias: auto_light_off
  initial_state: True
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 10
  condition:
    - condition: template
      value_template: '{{ (now().strftime("%s") | int | timestamp_custom("%H:%M")) == states.sensor.auto_light_stop.state }}'
  action:
    - service: homeassistant.turn_off
      entity_id: "group.lights"

#
# attempt to notify when things are down
#

- id: notify_ageathome_devices
  alias: 'notify_ageathome_devices'
  initial_state: on
  trigger:
    - platform: state
      entity_id: 
        - device_tracker.roughfog
        - device_tracker.dampcloud
        - device_tracker.roughwind
        - device_tracker.quietwater
  condition: 
    - condition: template
      value_template: >
        {{ ( trigger.from_state != None and trigger.to_state.state != trigger.from_state.state ) }}
  action:
    - service: notify.notify
      data_template:
        message: >
          AgeAtHome device {{ trigger.entity_id }} {{ state(trigger.entity_id)['attributes.friendly_name'] }}'s status just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

- id: notify_ageathome_devices_offline'
  alias: 'notify_ageathome_offline'
  trigger:
    - platform: state
      entity_id:
        - device_tracker.roughfog
        - device_tracker.dampcloud
        - device_tracker.roughwind
        - device_tracker.quietwater
  condition:
    - condition: template
      value_template: >
        {{ trigger.to_state == 'not_home' }}
  action:
    - service: notify.notify
      data_template:
        message: >
          AgeAtHome {{ trigger.entity_id.replace('device_tracker.','') }} is offline.

- id: notify_status_view
  alias: 'notify_status_view'
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.status_view
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state != None and trigger.to_state.state != trigger.from_state.state }}
  action:
    - service: notify.notify
      data_template:
        message: >
          System {{ trigger.entity_id }}'s status just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

#
# iOS NOTIFICATIONS
#

- id: notify_david
  alias: 'notify_david'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.dcmsiphone7
    - platform: state
      entity_id: device_tracker.davids_iphone
  condition: 
    condition: and
    conditions:
      - condition: time
        after: '06:00'
      - condition: time
        before: '22:00'
      - condition: template
        value_template: >
          {{ trigger.from_state != None and trigger.to_state.state != trigger.from_state.state }}
  action:
    - service: notify.notify
      data_template:
        message: >
          {{ trigger.entity_id }}'s location just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

- id: notify_ellen
  alias: 'notify_ellen'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: 
      - device_tracker.ellensiphone5
      - device_tracker.ellens_iphone
  condition: 
    condition: and
    conditions:
      - condition: time
        after: '06:00'
      - condition: time
        before: '22:00'
      - condition: template
        value_template: >
          {{ trigger.from_state != None and trigger.to_state.state != trigger.from_state.state }}
  action:
    - service: notify.notify
      data_template:
        message: >
          {{ trigger.entity_id }}'s location just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

- id: notify_keli
  alias: 'notify_keli'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: 
      - device_tracker.kelisiphone7
      - device_tracker.kelis_iphone
  condition: 
    condition: and
    conditions:
      - condition: time
        after: '06:00'
      - condition: time
        before: '22:00'
      - condition: template
        value_template: >
          {{ trigger.from_state != None and trigger.to_state.state != trigger.from_state.state }}
  action:
    - service: notify.notify
      data_template:
        message: >
          {{ trigger.entity_id }}'s location just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

- id: notify_riley
  alias: 'notify_riley'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: 
      - device_tracker.rileysiphone5
      - device_tracker.rileys_iphone
  condition: 
    condition: and
    conditions:
      - condition: time
        after: '06:00'
      - condition: time
        before: '22:00'
      - condition: template
        value_template: >
          {{ trigger.from_state != None and trigger.to_state.state != trigger.from_state.state }}
  action:
    - service: notify.notify
      data_template:
        message: >
          {{ trigger.entity_id }}'s location just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

#
# MQTT
#

- id: david_status
  alias: david_status
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.david_status
  action:
    - service: mqtt.publish
      data_template:
        topic: 'status/david'
        payload: >
          {"what":"david","date:",{{(now().timestamp()|int)}},"state":{{ states('sensor.david_status') }}}

- id: camera_offline
  alias: camera_offline
  trigger:
    platform: state
    entity_id:
      - camera.ageathome_kitchen
      - camera.ageathome_bathroom
      - camera.ageathome_frontdoor
      - camera.ageathome_road
    to: 'not home'
    for:
      minutes: 10
  action:
    - service: mqtt.publish
      data_template:
        topic: 'ageathome/status/camera'
        payload: >
          {"device":"{{ trigger.to_state.attributes.friendly_name }}","status":"offline"}

- id: notify_lowscore
  alias: very low score
  trigger:
    platform: numeric_state
    entity_id: sensor.last_why
    below: 0.50
  action:
    - service: mqtt.publish
      data_template:
        topic: 'ageathome/notify/score'
        payload: >
          {"location":{{states('sensor.last_where')|tojson}},"model":{{states('sensor.last_who')|tojson}},"class":{{states('sensor.last_what')|tojson}},"score":{{states('sensor.last_why')}}}

- id: notify_highscore
  alias: very high score
  trigger:
    platform: numeric_state
    entity_id: sensor.last_why
    above: 0.98
  action:
    - service: mqtt.publish
      data_template:
        topic: 'ageathome/notify/score'
        payload: >
          {"location":{{states('sensor.last_where')|tojson}},"model":{{states('sensor.last_who')|tojson}},"class":{{states('sensor.last_what')|tojson}},"score":{{states('sensor.last_why')}}}

###
### PUBLISH OUTPUT
###

- id: aah_not_home
  alias: aah_not_home
  initial_state: on
  trigger:
    - platform: mqtt
      topic: 'presence/+'
  condition: 
     - condition: template
       value_template: >
         {%- for state in states.group.people.attributes.entity_id -%}
           {%- set w = state.replace('sensor.','').replace('_location','')|lower -%}
           {%- if w == trigger.payload_json.class|lower and states(state)|lower != 'home' -%} 
            {{- true -}}
           {%- endif -%}
         {%- endfor -%}
#     - condition: template
#       value_template: '{{ states(("sensor.",trigger.payload_json.class,"_location")|join|lower) not in ("home","unknown") }}'
#     - condition: template
#       value_template: '{{ trigger.payload_json.class == "martin_c70" and states("sensor.david_location")|lower == "home" }}'
  action:
    - service: mqtt.publish
      data_template:
        topic: 'wrong/{{ trigger.payload_json.location }}/{{ trigger.payload_json.class }}'
        payload: >-
          {
           "type":"not_home",
           "triggered":{{(now().timestamp()|int)}},
           "device":{{trigger.payload_json.device|tojson}},
           "id":{{trigger.payload_json.id|tojson}},
           "where":{{trigger.payload_json.location|tojson}},
           "who":{{trigger.payload_json.model|tojson}},
           "what":{{trigger.payload_json.class|tojson}},
           "why":{{trigger.payload_json.score|float}},
           "date":{{trigger.payload_json.date|int}}
          }

#- id: sonos_volume_limiter
#  alias: Sonos Volume Limiter
#  initial_state: True
#  hide_entity: False
#  trigger:
#    platform: numeric_state
#    entity_id: media_player.play1
#    value_template: '{{ state.attributes.volume_level }}'
#    above: 0.35
#  condition:
#    platform: time
#    after: '08:00:00'
#    before: '20:00:00'
#  action:
#    - service: media_player.volume_set
#      data_template:
#        entity_id: media_player.play1
#        volume_level: 0.34

##
## DUMPS
##

- id: publish_automations
  alias: 'publish_automations'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.automation != None }}'
    - platform: state
      entity_id: states.automation
  action:
    - service: mqtt.publish
      data_template:
        topic: 'state/automation/all'
        payload: >
          {%- for state in states.automation -%}
            {%- if loop.first -%}{"category":"automation","date":{{ (now().timestamp()|int) }},"items":[
            {%- else -%},
            {%- endif -%} {"name":"{{state.name|lower}}","state":"{{state.state}}","last_triggerd":"{{state.attributes.last_triggered}}"}
          {%- endfor -%}]}

- id: publish_binary_sensors
  alias: 'publish_binary_sensors'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.binary_sensor != None }}'
    - platform: state
      entity_id: states.binary_sensor
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/binary_sensor/all'
        payload: >
          {% for state in states.binary_sensor -%}
            {%- if loop.first -%} {"category":"binary_sensor","date":{{ (now().timestamp()|int) }},"items":[
            {%- else -%},
            {%- endif -%} {"name":"{{state.name|lower}}","state":"{{state.state}}","attributes":{{state.attributes|length}}}
          {%- endfor -%}]}

- id: publish_cameras
  alias: 'publish_cameras'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.camera != None }}'
    - platform: state
      entity_id: states.camera
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/camera/all'
        payload: >
          {% for state in states.camera -%}
            {%- if loop.first -%}{"category":"camera","date":{{ (now().timestamp()|int) }},"items":[
            {%- else -%},
            {%- endif -%} {"name":"{{state.name|lower}}","state":"{{state.state}}","attributes":{{state.attributes|length}}}
          {%- endfor -%}]}

- id: publish_device_trackers
  alias: 'publish_device_trackers'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.device_tracker != None }}'
    - platform: state
      entity_id: states.device_tracker
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/device_tracker/all'
        payload: >
         {% for state in states.device_tracker -%}
           {%- if loop.first -%}{"category":"device_tracker","date":{{ (now().timestamp()|int) }},"items":[
           {%- elif loop.last -%}
             {%- if state.attributes.source_type != None -%}
               {"name":"{{ state.name | lower }}","state":"{{state.state}}","attributes":{{state.attributes|length}}}
             {%- endif -%}
           {%- else -%}
             {%- if state.attributes.source_type != None -%}
               {"name":"{{ state.name | lower }}","state":"{{state.state}}","attributes":{{state.attributes|length}}},
             {%- endif -%}
           {%- endif -%}
          {%- endfor -%}]}

- id: publish_media_players
  alias: 'publish_media_players'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.media_player != None }}'
    - platform: state
      entity_id: states.media_player
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/media_player/all'
        payload: >
          {% for state in states.media_player -%}
            {%- if loop.first -%}{"category":"media_player","date":{{ (now().timestamp()|int) }},"items":[
            {%- else -%},
            {%- endif -%} {"name":"{{state.name|lower}}","state":"{{state.state}}","attributes":{{state.attributes|length}}}
          {%- endfor -%}]}

- id: publish_sensors
  alias: 'publish_sensors'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.sensor != None }}'
    - platform: state
      entity_id: states.sensor
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/sensor/all'
        payload: >
         {% for state in states.sensor -%}
           {%- if loop.first -%}{"category":"sensor","date":{{ (now().timestamp()|int) }},"items":[
           {%- elif loop.last -%}
             {"name":"{{ state.name | lower }}","state":{{ state.state|tojson }}}
           {%- else -%}
             {"name":"{{ state.name | lower }}","state":{{ state.state|tojson }}},
           {%- endif -%}
          {%- endfor -%}]}

- id: publish_zones
  alias: 'publish_zones'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.zone != None }}'
    - platform: state
      entity_id: states.zone
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/zone/all'
        payload: >
          {% for state in states.zone -%}
            {%- if loop.first -%} {"category":"zone","date":{{ (now().timestamp()|int) }},"items":[
            {%- else -%},
            {%- endif -%} {"name":"{{state.name|lower}}","state":"{{state.state}}","attributes":{"radius":{{state.attributes.radius}},"latitude":{{state.attributes.latitude}},"longitude":{{state.attributes.longitude}} }}
          {%- endfor -%}]}

- id: publish_states
  alias: 'publish_states'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.state != None }}'
    - platform: state
      entity_id: states.state
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/all'
        payload: >
          {%- for i in states -%}
            {%- if loop.first -%}[{%- elif loop.last -%}]{%- else -%},{%- endif -%}
            {"name":"{{ i.name }}","domain":"{{ i.domain }}"}
          {%- endfor -%}

- id: debug_automation
  alias: debug_automation
  initial_state: on
  trigger:
    - platform: state
      entity_id: states.automation
  action:
    - service: mqtt.publish
      data_template:
        topic: 'debug/{{ trigger.platform }}/{{ trigger.entity_id }}'
        retain: false
        payload: >-
          {%- macro dumpState(statePrefix, stateObj) -%}
            {{statePrefix ~ ": "}} {{- stateObj.state }}{{- "\n" -}}
            {{statePrefix ~ ".entity_id: "}} {{- stateObj.entity_id }}{{- "\n" -}}
            {{statePrefix ~ ".domain: "}} {{- stateObj.domain }}{{- "\n" -}}
            {{statePrefix ~ ".object_id: "}} {{- stateObj.object_id }}{{- "\n" -}}
            {{statePrefix ~ ".name: "}} {{- stateObj.name }}{{- "\n" -}}
            {{statePrefix ~ ".last_updated: "}} {{- stateObj.last_updated }}{{- "\n" -}}
            {{statePrefix ~ ".last_changed: "}} {{- stateObj.last_changed }}{{- "\n" -}}
            {%- for attrib in stateObj.attributes | sort() %}
              {%- if attrib is defined -%}
              {{- statePrefix ~ ".attributes." ~ attrib ~ ": " -}} {{- stateObj.attributes[attrib] -}}
              {{- "\n" -}}
              {%- endif -%}
            {%- endfor -%}
          {%- endmacro -%}
          {% set p = trigger.platform %}
          {{"trigger.platform: "}} {{ p }}{{- "\n" -}}
          {%- if p == "mqtt" -%}
            {{"trigger.topic: "}} {{ trigger.topic }}{{- "\n" -}}
            {{"trigger.payload: "}} {{ trigger.payload }}{{- "\n" -}}
            {{"trigger.payload_json: "}} {{ trigger.payload_json }}{{- "\n" -}}
            {{"trigger.qos: "}} {{ trigger.qos }}{{- "\n" -}}
            {%- endif -%}
            {%- if p == "event" or p == "sun" or p == "zone" -%}
            {{"trigger.event: "}} {{ trigger.event }}{{- "\n" -}}
          {%- endif -%}
          {%- if p == "numeric_state" -%}
            {{"trigger.above: "}} {{ trigger.above }}{{- "\n" -}}
            {{"trigger.below: "}} {{trigger.below }}{{- "\n" -}}
          {%- endif -%}
          {%- if p == "state" -%}
            {{"trigger.for: "}} {{ trigger.for }}{{- "\n" -}}
          {%- endif -%}
          {%- if p == "time" -%}
            {{"trigger.now: "}} {{ trigger.now }}{{- "\n" -}}
          {%- endif -%}
          {%- if p == "zone" -%}
            {{"trigger.zone: "}} {{ trigger.zone }}{{- "\n" -}}
          {%- endif -%}
          {%- if p == "state" or p == "numeric_state" or p == "template" or p == "zone" -%}
            {{"trigger.entity_id: "}} {{ trigger.entity_id }}{{- "\n" -}}{{- "\n" -}}
            {{"trigger.from_state: "}} {{- "\n" -}}
            -------------------{{- "\n" -}}
            {{ dumpState("trigger.from_state", trigger.from_state) }} {{- "\n" -}}
            trigger.to_state:{{- "\n" -}}
            -----------------{{- "\n" -}}
            {{ dumpState("trigger.to_state", trigger.to_state) }}
          {%- endif -%}
