- id: auto_light_on_enabled
  alias: auto_light_on_enabled
  trigger:
    platform: state
    entity_id: input_slider.auto_light_minutes, input_slider.auto_light_duration
  action:
  - service: homeassistant.turn_on
    data:
      entity_id:
        - automation.auto_light_on
  - service: homeassistant.turn_on
    data:
      entity_id:
        - automation.auto_light_off

- id: auto_light_on
  alias: auto_light_on
  initial_state: True
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 10
  condition:
    - condition: template
      value_template: '{{ (now().strftime("%s") | int | timestamp_custom("%H:%M")) == states.sensor.auto_light_start.state }}'
  action:
    - service: homeassistant.turn_on
      entity_id: "group.lights"

- id: auto_light_off
  alias: auto_light_off
  initial_state: True
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 10
  condition:
    - condition: template
      value_template: '{{ (now().strftime("%s") | int | timestamp_custom("%H:%M")) == states.sensor.auto_light_stop.state }}'
  action:
    - service: homeassistant.turn_off
      entity_id: "group.lights"

#
# iOS NOTIFICATIONS
#

- id: notify_david
  alias: 'notify_david'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.dcmsiphone7
    - platform: state
      entity_id: device_tracker.davids_iphone
  condition: 
    condition: and
    conditions:
      - condition: time
        after: '06:00'
      - condition: time
        before: '22:00'
      - condition: template
        value_template: >
          {{ trigger.from_state != None and trigger.to_state.state != trigger.from_state.state }}
  action:
    - service: notify.notify
      data_template:
        message: >
          {{ trigger.entity_id }}'s location just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

- id: notify_ellen
  alias: 'notify_ellen'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.ellensiphone5
  condition: 
    condition: and
    conditions:
      - condition: time
        after: '06:00'
      - condition: time
        before: '22:00'
      - condition: template
        value_template: >
          {{ trigger.from_state != None and trigger.to_state.state != trigger.from_state.state }}
  action:
    - service: notify.notify
      data_template:
        message: >
          {{ trigger.entity_id }}'s location just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

- id: notify_keli
  alias: 'notify_keli'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.kelisiphone7
  condition: 
    condition: and
    conditions:
      - condition: time
        after: '06:00'
      - condition: time
        before: '22:00'
      - condition: template
        value_template: >
          {{ trigger.from_state != None and trigger.to_state.state != trigger.from_state.state }}
  action:
    - service: notify.notify
      data_template:
        message: >
          {{ trigger.entity_id }}'s location just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

- id: notify_riley
  alias: 'notify_riley'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.rileysiphone5
  condition: 
    condition: and
    conditions:
      - condition: time
        after: '06:00'
      - condition: time
        before: '22:00'
      - condition: template
        value_template: >
          {{ trigger.from_state != None and trigger.to_state.state != trigger.from_state.state }}
  action:
    - service: notify.notify
      data_template:
        message: >
          {{ trigger.entity_id }}'s location just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

#
# MQTT
#

- id: aah_family_detected
  alias: 'aah_family_detected'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.family_detected
    to: 'on'
  action:
    - service: mqtt.publish
      data_template:
        topic: 'what/family'
        payload: >
          {"what":"family","date:",{{(now().timestamp()|int)}},"state":"{{ trigger.to_state.state }}"}

- id: aah_device_detected
  alias: 'aah_device_detected'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.iphones
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'what/{{trigger.entity_id}}'
        payload: >
          {"what":"{{trigger.entity_id}}","date":{{(now().timestamp()|int)}},"state":"{{trigger.to_state.state}}"

#- id: aah_mqtt_camera_offline
#  alias: 'Notify if any AAH sensor is unknown for 10 minutes'
#  trigger:
#    platform: state
#    entity_id:
#      - sensor.kitchen_camera
#      - sensor.bathroom_camera
#      - sensor.frontdoor_camera
#      - sensor.road_camera
#    state: None
#    for:
#      minutes: 10
#  action:
#    - service: mqtt.publish
#      data_template:
#        topic: 'device/camera/{{trigger.to_state.attributes.friendly_name}}'
#        payload: >
#          {"device":"{{ trigger.to_state.attributes.friendly_name }}","status":"offline"}
#
#- id: aah_notify_lowscore
#  alias: very low score
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.last_why
#    below: 0.50
#  action:
#    - service: notify.notify
#      data_template:
#        message: >
#          VERY LOW {{ states.sensor.last_who }} saw {{ states.sensor.last_what }} {{ states.sensor.last_why }}
#
#- id: aah_notify_highscore
#  alias: very high score
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.last_why
#    above: 0.99
#  action:
#    - service: notify.notify
#      data_template:
#        message: >
#          VERY HIGH {{ states.sensor.last_who }} saw {{ states.sensor.last_what }} {{ states.sensor.last_why }}
#
#- id: sonos_volume_limiter
#  alias: Sonos Volume Limiter
#  initial_state: True
#  hide_entity: False
#  trigger:
#    platform: numeric_state
#    entity_id: media_player.play1
#    value_template: '{{ state.attributes.volume_level }}'
#    above: 0.35
#  condition:
#    platform: time
#    after: '08:00:00'
#    before: '20:00:00'
#  action:
#    - service: media_player.volume_set
#      data_template:
#        entity_id: media_player.play1
#        volume_level: 0.34

##
## DUMPS
##

- id: publish_automations
  alias: 'publish_automations'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.automation != None }}'
    - platform: state
      entity_id: states.automation
  action:
    - service: mqtt.publish
      data_template:
        topic: 'state/automation/all'
        payload: >
          {%- for state in states.automation -%}
            {%- if loop.first -%}{"category":"automation","date":{{ (now().timestamp()|int) }},"items":[
            {%- else -%},
            {%- endif -%} {"name":"{{state.name|lower}}","state":"{{state.state}}","last_triggerd":"{{state.attributes.last_triggered}}"}
          {%- endfor -%}]}

- id: publish_binary_sensors
  alias: 'publish_binary_sensors'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.binary_sensor != None }}'
    - platform: state
      entity_id: states.binary_sensor
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/binary_sensor/all'
        payload: >
          {% for state in states.binary_sensor -%}
            {%- if loop.first -%} {"category":"binary_sensor","date":{{ (now().timestamp()|int) }},"items":[
            {%- else -%},
            {%- endif -%} {"name":"{{state.name|lower}}","state":"{{state.state}}","attributes":{{state.attributes|length}}}
          {%- endfor -%}]}

- id: publish_cameras
  alias: 'publish_cameras'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.camera != None }}'
    - platform: state
      entity_id: states.camera
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/camera/all'
        payload: >
          {% for state in states.camera -%}
            {%- if loop.first -%}{"category":"camera","date":{{ (now().timestamp()|int) }},"items":[
            {%- else -%},
            {%- endif -%} {"name":"{{state.name|lower}}","state":"{{state.state}}","attributes":{{state.attributes|length}}}
          {%- endfor -%}]}

- id: publish_device_trackers
  alias: 'publish_device_trackers'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.device_tracker != None }}'
    - platform: state
      entity_id: states.device_tracker
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/device_tracker/all'
        payload: >
         {% for state in states.device_tracker -%}
           {%- if loop.first -%}{"category":"device_tracker","date":{{ (now().timestamp()|int) }},"items":[
           {%- elif loop.last -%}
             {%- if state.attributes.source_type != None -%}
               {"name":"{{ state.name | lower }}","state":"{{state.state}}","attributes":{{ state.attributes|length}}}
             {%- endif -%}
           {%- else -%}
             {%- if state.attributes.source_type != None -%}
               {"name":"{{ state.name | lower }}","state":"{{state.state}}","attributes":{{ state.attributes|length}}},
             {%- endif -%}
           {%- endif -%}
          {%- endfor -%}]}

- id: publish_media_players
  alias: 'publish_media_players'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.media_player != None }}'
    - platform: state
      entity_id: states.media_player
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/media_player/all'
        payload: >
          {% for state in states.media_player -%}
            {%- if loop.first -%}{"category":"media_player","date":{{ (now().timestamp()|int) }},"items":[
            {%- else -%},
            {%- endif -%} {"name":"{{state.name|lower}}","state":"{{state.state}}","attributes":{{state.attributes|length}}}
          {%- endfor -%}]}

- id: publish_sensors
  alias: 'publish_sensors'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.sensor != None }}'
    - platform: state
      entity_id: states.sensor
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/sensor/all'
        payload: >
         {% for state in states.sensor -%}
           {%- if loop.first -%}{"category":"sensor","date":{{ (now().timestamp()|int) }},"items":[
           {%- elif loop.last -%}
             {"name":"{{ state.name | lower | urlencode }}","state":"{{ state.state }}"}
           {%- else -%}
             {"name":"{{ state.name | lower | urlencode }}","state":"{{ state.state }}"},
           {%- endif -%}
          {%- endfor -%}]}

- id: publish_zones
  alias: 'publish_zones'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.zone != None }}'
    - platform: state
      entity_id: states.zone
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/zone/all'
        payload: >
          {% for state in states.zone -%}
            {%- if loop.first -%} {"category":"zone","date":{{ (now().timestamp()|int) }},"items":[
            {%- else -%},
            {%- endif -%} {"name":"{{state.name|lower}}","state":"{{state.state}}","attributes":{"radius":{{state.attributes.radius}},"latitude":{{state.attributes.latitude}},"longitude":{{state.attributes.longitude}} }}
          {%- endfor -%}]}

- id: publish_states
  alias: 'publish_states'
  initial_state: 'on'
  trigger:
    - platform: template
      value_template: '{{ states.state != None }}'
    - platform: state
      entity_id: states.state
  action: 
    - service: mqtt.publish
      data_template:
        topic: 'state/all'
        payload: >
          {%- for i in states -%}
            {%- if loop.first -%}[{%- elif loop.last -%}]{%- else -%},{%- endif -%}
            {"name":"{{ i.name }}","domain":"{{ i.domain }}"}
          {%- endfor -%}

- id: debug_automation
  alias: debug_automation
  initial_state: on
  trigger:
    - platform: state
      entity_id: states.automation
  action:
    - service: mqtt.publish
      data_template:
        topic: 'debug/{{ trigger.platform }}/{{ trigger.entity_id }}'
        retain: false
        payload: >-
          {%- macro dumpState(statePrefix, stateObj) -%}
            {{statePrefix ~ ": "}} {{- stateObj.state }}{{- "\n" -}}
            {{statePrefix ~ ".entity_id: "}} {{- stateObj.entity_id }}{{- "\n" -}}
            {{statePrefix ~ ".domain: "}} {{- stateObj.domain }}{{- "\n" -}}
            {{statePrefix ~ ".object_id: "}} {{- stateObj.object_id }}{{- "\n" -}}
            {{statePrefix ~ ".name: "}} {{- stateObj.name }}{{- "\n" -}}
            {{statePrefix ~ ".last_updated: "}} {{- stateObj.last_updated }}{{- "\n" -}}
            {{statePrefix ~ ".last_changed: "}} {{- stateObj.last_changed }}{{- "\n" -}}
            {%- for attrib in stateObj.attributes | sort() %}
              {%- if attrib is defined -%}
              {{- statePrefix ~ ".attributes." ~ attrib ~ ": " -}} {{- stateObj.attributes[attrib] -}}
              {{- "\n" -}}
              {%- endif -%}
            {%- endfor -%}
          {%- endmacro -%}
          {% set p = trigger.platform %}
          {{"trigger.platform: "}} {{ p }}{{- "\n" -}}
          {%- if p == "mqtt" -%}
            {{"trigger.topic: "}} {{ trigger.topic }}{{- "\n" -}}
            {{"trigger.payload: "}} {{ trigger.payload }}{{- "\n" -}}
            {{"trigger.payload_json: "}} {{ trigger.payload_json }}{{- "\n" -}}
            {{"trigger.qos: "}} {{ trigger.qos }}{{- "\n" -}}
            {%- endif -%}
            {%- if p == "event" or p == "sun" or p == "zone" -%}
            {{"trigger.event: "}} {{ trigger.event }}{{- "\n" -}}
          {%- endif -%}
          {%- if p == "numeric_state" -%}
            {{"trigger.above: "}} {{ trigger.above }}{{- "\n" -}}
            {{"trigger.below: "}} {{trigger.below }}{{- "\n" -}}
          {%- endif -%}
          {%- if p == "state" -%}
            {{"trigger.for: "}} {{ trigger.for }}{{- "\n" -}}
          {%- endif -%}
          {%- if p == "time" -%}
            {{"trigger.now: "}} {{ trigger.now }}{{- "\n" -}}
          {%- endif -%}
          {%- if p == "zone" -%}
            {{"trigger.zone: "}} {{ trigger.zone }}{{- "\n" -}}
          {%- endif -%}
          {%- if p == "state" or p == "numeric_state" or p == "template" or p == "zone" -%}
            {{"trigger.entity_id: "}} {{ trigger.entity_id }}{{- "\n" -}}{{- "\n" -}}
            {{"trigger.from_state: "}} {{- "\n" -}}
            -------------------{{- "\n" -}}
            {{ dumpState("trigger.from_state", trigger.from_state) }} {{- "\n" -}}
            trigger.to_state:{{- "\n" -}}
            -----------------{{- "\n" -}}
            {{ dumpState("trigger.to_state", trigger.to_state) }}
          {%- endif -%}
