  include:
    entities:
      - sensor.externalip
      # - binary_sensor.fletcher_fordflex_road
      # - binary_sensor.martin_rtv1100_road
      # - binary_sensor.martin_sprinter_road
      # - binary_sensor.martin_suburban_road
      # - binary_sensor.martin_xc90_road
      # - binary_sensor.martin_c30_road
      - binary_sensor.martin_c70_road
      - binary_sensor.other_road
      - sensor.martin_road_count
      - sensor.martin_road_ratio
      - sensor.martin_road_time
      - sensor.fletcher_road_count
      - sensor.fletcher_road_ratio
      - sensor.fletcher_road_time
      - sensor.other_road_count
      - sensor.other_road_ratio
      - sensor.other_road_time
      # motion in location
      - binary_sensor.bathroom_motion
      - binary_sensor.exterior_motion
      - binary_sensor.frontdoor_motion
      - binary_sensor.interior_motion
      - binary_sensor.kitchen_motion
      - binary_sensor.road_motion
      # entity in location (6 entities; 3 locations)
      - binary_sensor.david_bathroom
      - binary_sensor.david_frontdoor
      - binary_sensor.david_interior
      - binary_sensor.david_kitchen
      - binary_sensor.ellen_bathroom
      - binary_sensor.ellen_frontdoor
      - binary_sensor.ellen_interior
      - binary_sensor.ellen_kitchen
      - binary_sensor.hali_bathroom
      - binary_sensor.hali_frontdoor
      - binary_sensor.hali_interior
      - binary_sensor.hali_kitchen
      - binary_sensor.ian_bathroom
      - binary_sensor.ian_frontdoor
      - binary_sensor.ian_interior
      - binary_sensor.ian_kitchen
      - binary_sensor.keli_bathroom
      - binary_sensor.keli_frontdoor
      - binary_sensor.keli_interior
      - binary_sensor.keli_kitchen
      - binary_sensor.riley_bathroom
      - binary_sensor.riley_frontdoor
      - binary_sensor.riley_interior
      - binary_sensor.riley_kitchen
      # entity @ home (6 entities; bayesian)
      - binary_sensor.david_home
      - binary_sensor.ellen_home
      - binary_sensor.hali_home
      - binary_sensor.ian_home
      - binary_sensor.keli_home
      - binary_sensor.riley_home
      # classifier wrong
      - binary_sensor.kitchen_wrong
      - binary_sensor.bathroom_wrong
      - binary_sensor.frontdoor_wrong
      - binary_sensor.road_wrong
      # entity device tracker (iOS)
      - device_tracker.dcmsiphone7
      - device_tracker.ellensiphone5
      - device_tracker.halisiphone
      - device_tracker.ianmartinsiphone
      - device_tracker.kelisiphone7
      - device_tracker.rileysiphone5
      # location
      - sensor.bathroom_ago
      - sensor.bathroom_motion_count
      - sensor.bathroom_motion_time
      - sensor.bathroom_what
      # meta-sensor
      - sensor.count_automations
      - sensor.count_binary_sensors
      - sensor.count_cameras
      - sensor.count_device_trackers
      - sensor.count_media_players
      - sensor.count_sensors
      - sensor.count_zones
      - sensor.david_bathroom_count
      - sensor.david_bathroom_ratio
      - sensor.david_bathroom_time
      - sensor.david_frontdoor_count
      - sensor.david_frontdoor_ratio
      - sensor.david_frontdoor_time
      - sensor.david_kitchen_count
      - sensor.david_kitchen_ratio
      - sensor.david_kitchen_time
      - sensor.david_location
      - sensor.david_plex
      - sensor.ellen_bathroom_count
      - sensor.ellen_bathroom_ratio
      - sensor.ellen_bathroom_time
      - sensor.ellen_frontdoor_count
      - sensor.ellen_frontdoor_ratio
      - sensor.ellen_frontdoor_time
      - sensor.ellen_kitchen_count
      - sensor.ellen_kitchen_ratio
      - sensor.ellen_kitchen_time
      - sensor.ellen_location
      - sensor.exterior_motion_ratio
      - sensor.frontdoor_ago
      - sensor.frontdoor_motion_count
      - sensor.frontdoor_motion_time
      - sensor.frontdoor_what
      - sensor.hali_bathroom_count
      - sensor.hali_bathroom_ratio
      - sensor.hali_bathroom_time
      - sensor.hali_frontdoor_count
      - sensor.hali_frontdoor_ratio
      - sensor.hali_frontdoor_time
      - sensor.hali_kitchen_count
      - sensor.hali_kitchen_ratio
      - sensor.hali_kitchen_time
      - sensor.hali_location
      - sensor.ian_bathroom_count
      - sensor.ian_bathroom_ratio
      - sensor.ian_bathroom_time
      - sensor.ian_frontdoor_count
      - sensor.ian_frontdoor_ratio
      - sensor.ian_frontdoor_time
      - sensor.ian_kitchen_count
      - sensor.ian_kitchen_ratio
      - sensor.ian_kitchen_time
      - sensor.ian_location
      - sensor.interior_motion_ratio
      - sensor.keli_bathroom_count
      - sensor.keli_bathroom_ratio
      - sensor.keli_bathroom_time
      - sensor.keli_frontdoor_count
      - sensor.keli_frontdoor_ratio
      - sensor.keli_frontdoor_time
      - sensor.keli_kitchen_count
      - sensor.keli_kitchen_ratio
      - sensor.keli_kitchen_time
      - sensor.keli_location
      - sensor.kitchen_ago
      - sensor.kitchen_motion_count
      - sensor.kitchen_motion_time
      - sensor.kitchen_what
      - sensor.last_ago
      - sensor.last_what
      - sensor.last_when
      - sensor.play1_state
      - sensor.play3_state
      - sensor.riley_bathroom_count
      - sensor.riley_bathroom_ratio
      - sensor.riley_bathroom_time
      - sensor.riley_frontdoor_count
      - sensor.riley_frontdoor_ratio
      - sensor.riley_frontdoor_time
      - sensor.riley_kitchen_count
      - sensor.riley_kitchen_ratio
      - sensor.riley_kitchen_time
      - sensor.riley_location
      - sensor.road_ago
      - sensor.road_motion_count
      - sensor.road_motion_time
      - sensor.road_what
