ageathome_learning:
  name: ageathome_learning
  initial: false
  icon: mdi:train

ageathome_notify_email:
  name: ageathome_notify_email
  initial: false
  icon: mdi:email

ageathome_notify_gate:
  name: ageathome_notify_gate
  initial: true
  icon: mdi:gate

ageathome_notify_poolhouse:
  name: ageathome_notify_poolhouse
  initial: true
  icon: mdi:pool

