ageathome_learning:
  name: ageathome_learning
  initial: false
  icon: mdi:train

ageathome_notify_email:
  name: ageathome_notify_email
  initial: false
  icon: mdi:email

ageathome_notify_gate:
  name: ageathome_notify_gate
  initial: true
  icon: mdi:gate

ageathome_notify_poolhouse:
  name: ageathome_notify_poolhouse
  initial: true
  icon: mdi:pool

ageathome_notify_kitchen:
  name: ageathome_notify_kitchen
  initial: false
  icon: mdi:stove

ageathome_notify_bathroom:
  name: ageathome_notify_bathroom
  initial: false
  icon: mdi:anchor

ageathome_notify_frontdoor:
  name: ageathome_notify_frontdoor
  initial: false
  icon: mdi:door

ageathome_notify_road:
  name: ageathome_notify_road
  initial: false
  icon: mdi:road

