
# ageathome

rough-fog:
  mac: B8:27:EB:D0:95:AD
  name: 'ageathome_kitchen'
  hide_if_away: false
  icon: mdi:webcam
  picture: http://farm5.static.flickr.com/4100/4930862762_4abbd2b5b3_m.jpg
  track: true
  vendor: Raspberry Pi Foundation

quiet-water:
  mac: B8:27:EB:90:6F:4A
  name: 'ageathome_road'
  hide_if_away: false
  icon: mdi:webcam
  picture: http://farm5.static.flickr.com/4100/4930862762_4abbd2b5b3_m.jpg
  track: true
  vendor: Raspberry Pi Foundation

damp-cloud:
  mac: B8:27:EB:01:E6:05
  name: 'ageathome_bathroom'
  hide_if_away: false
  icon: mdi:webcam
  picture: http://farm5.static.flickr.com/4100/4930862762_4abbd2b5b3_m.jpg
  track: true
  vendor: Raspberry Pi Foundation

# 192.168.1.37
rough-wind:
  mac: B8:27:EB:BD:1D:F3
  name: 'ageathome_frontdoor'
  hide_if_away: false
  icon: mdi:webcam
  picture: http://farm5.static.flickr.com/4100/4930862762_4abbd2b5b3_m.jpg
  track: true
  vendor: Raspberry Pi Foundation

# 192.168.1.38
aged-bush:
  mac: B8:27:EB:51:A7:48
  name: 'ageathome_gate'
  hide_if_away: false
  icon: mdi:webcam
  picture: http://farm5.static.flickr.com/4100/4930862762_4abbd2b5b3_m.jpg
  track: true
  vendor: Raspberry Pi Foundation

# 192.168.1.39
lively-paper:
  mac: B8:27:EB:DD:A0:94
  name: 'ageathome_poolhouse'
  hide_if_away: false
  icon: mdi:webcam
  picture: http://farm5.static.flickr.com/4100/4930862762_4abbd2b5b3_m.jpg
  track: true
  vendor: Raspberry Pi Foundation

