#!/bin/csh -fb
sudo docker cp known_devices.yaml homeassistant:/config/known_devices.yaml
sudo docker cp configuration.yaml homeassistant:/config/configuration.yaml
sudo docker cp groups.yaml homeassistant:/config/groups.yaml
sudo docker cp templates.yaml homeassistant:/config/templates.yaml
sudo docker cp secrets.yaml homeassistant:/config/secrets.yaml 
sudo docker restart homeassistant
