ageathome_learning:
  name: ageathome_learning
  initial: false
  icon: mdi:train

ageathome_notify_email:
  name: ageathome_notify_email
  initial: false
  icon: mdi:email

ageathome_notify_gate:
  name: ageathome_notify_gate
  initial: true
  icon: mdi:gate

ageathome_notify_poolhouse:
  name: ageathome_notify_poolhouse
  initial: true
  icon: mdi:pool

name: My Awesome Home

views:
  - icon: mdi:people
    title: CAMERAS
    cards:
    - type: picture-entity
      entity: camera.ageathome_road
    - type: picture-entity
      entity: camera.ageathome_gate
    - type: picture-entity
      entity: camera.ageathome_frontdoor
    - type: picture-entity
      entity: camera.ageathome_kitchen
    - type: picture-entity
      entity: camera.ageathome_poolhouse
    - type: picture-entity
      entity: camera.ageathome_bathroom
  - icon: mdi:toggle-switch
    title: Switches
    cards:
    - type: entities
      title: Controls
      entities:
        - input_boolean.ageathome_learning
        - input_boolean.ageathome_notify_email
        - input_boolean.ageathome_notify_gate
        - input_boolean.ageathome_notify_poolhouse
