#!/bin/csh -fb

set dir = "$cwd/$0:h"

if ($?share == 0) set share = "/usr/share/hassio"
if ($?config == 0) set config = "$share/homeassistant"
if ($?addons == 0) set addons = "$share/addons/local"

# copy CONFIGURATION
set files = ( known_devices.yaml configuration.yaml groups.yaml automations.yaml templates.yaml logger.yaml customize.yaml secrets.yaml )
echo -n "Copying configuration ["
foreach file ( $files )
  echo -n "$file "
  cp "$dir/config/$file" "$config/$file"
end
echo "]"

# copy ADDONS
foreach i ( "$dir"/addons/* )
  echo -n "Copying $i:t ["
  if (-d "$i") then
    mkdir -p "$addons/$i:t"
    foreach j ( "$i"/* )
      echo -n "$j:t "
      if (-d "$j") then
        mkdir -p "$addons/$i:t/$j:t"
        foreach k ( "$j"/* )
          echo -n "$k:t "
          cp "$k" "$addons"/"$i:t"/"$j:t"/"$k:t"
        end
      else
        cp "$j" "$addons"/"$i:t"/"$j:t"
      endif
    end
  else
    cp "$j" "$addons"/"$i:t"/"$j:t"
  endif
  echo "]"
end
