#!/bin/bash
who=$(whoami)
if [[ "${who}" != "root" ]]; then
  echo "Please run as root; e.g. sudo $*"
  exit
fi
apt-get update -y
apt-get upgrade -y
apt-get install jq
apt-get install curl
apt-get install docker.io
apt-get install socat
curl -sL https://raw.githubusercontent.com/home-assistant/hassio-build/master/install/hassio_install | bash -s
echo "Please wait while server initializes; access at http://localhost:8123/"
