#!/bin/csh -fb
set docker = `groups "$user" | sed "s/.*docker.*/true/"`
if ($#docker && $docker == "true") then
  docker restart homeassistant
else
  echo "$0:t -- use sudo or add $user to docker group"
endif
